### ISSUE TITLE
Активация голосом

### ISSUE THREAD

**Issue by pastukhov** [uzyovoys/aggregate#1]
Добррый день, планируется ли реализация голосовой активации?

**Comment by morfeusys** [comment]
Конечно. С открытым API это может сделать вообще кто-угодно.

**Comment by Vladimir070381** [comment]
не пойму где все настройки?и описания?

**Comment by Vladimir070381** [comment]
как это сделать?

**Comment by morfeusys** [comment]
Дубликат https://github.com/uzyovoys/aggregate/issues/2
