### ISSUE TITLE
[asr-google] Какой ключ получить?

### ISSUE THREAD

**Issue by Menelion** [uzyovoys/aggregate#11]
Начал проходить процедуру получения API-ключа для _asr-google_. Их Credentials wizard спрашивает меня, какой из четырёх ключей я хочу получить: 
- Server key
- Browser key
- Android key
- IOs Key

А я даже не знаю. Выбрал по наитию _Server key_, а оно меня спрашивает, от каких IP-адресов разрешать. Опционально, но таки напрягло.  
Собственно, вопрос/просьба уточнить в readme, какой ключ нужно получить :).

**Comment by ivanbalashov239** [comment]
@Oire  там есть поисковая строка, наберите speech, и выберите speech api, будет ссылка `https://console.cloud.google.com/apis/api/speech/overview?project=<PROJECT_NAME>` с вашим именем проекта.

**Comment by UUSR** [comment]
Получайте Browser key. У меня только с ним Speech завёлся.

**Comment by Menelion** [comment]
@seniorivn, так и делаю. В результате перехожу на тот самый визард и получаю четыре ключа на выбор)  
@UUSR, спасибо, попробую!

**Comment by ivanbalashov239** [comment]
@Oire пардон, возможно, я что то упустил в описании, у меня, как мне показалось сразу был только один ключ и всё заработало.

**Comment by morfeusys** [comment]
Добавил в описание получения ключа про Browser key

**Comment by Menelion** [comment]
Спасибо!
