### ISSUE TITLE
com.aggregate.detector.key.keydetector

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#12]
что ему нужно от меня?

**Comment by ivanbalashov239** [comment]
ничего, это вам что то нужно от него, не потрудитесь сказать, что именно?

**Comment by Vladimir070381** [comment]
забиндил кнопку чтоб он слушал!нажимаю ее и ни че не происходит

**Comment by ivanbalashov239** [comment]
@Vladimir070381 ну это же альфа, приведите вывод из консоли хотя бы.

**Comment by Vladimir070381** [comment]
как скопироать консоль?

**Comment by ivanbalashov239** [comment]
@Vladimir070381 Какая ОС? Какое приложение терминала? В гугле смотрели?

**Comment by Vladimir070381** [comment]
винда7( 32) больше не знаю

**Comment by Vladimir070381** [comment]
windows system 32 cmd.exe

**Comment by ivanbalashov239** [comment]
@Vladimir070381 http://lmgtfy.com/?q=windows+7+copy+from+command+line

**Comment by Vladimir070381** [comment]
все хорош я все равно не пойму че нужно

**Comment by Vladimir070381** [comment]
подожду пока ее нормально настроят!

**Comment by ivanbalashov239** [comment]
@Vladimir070381  в следующий раз сразу так и поступайте.

**Comment by Vladimir070381** [comment]
я думаю кто то подскажет как скопироать без танцев с бубном

**Comment by morfeusys** [comment]
@Vladimir070381 Вы тестируете альфа-версию. Это не коробочное решение "поставил и работает". Поэтому можно столкнуться с проблемами.
