### ISSUE TITLE
[cmd.datetime.date] английская локаль

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#14]
в Linux используется английская локаль, агрегат говорит по русски, но англискую строку(03 марч фёрсдэй)  думаю локаль нужно брать всегда русскую(точне в соответствии с языком используемым в агрегате)

**Comment by morfeusys** [comment]
fixed https://github.com/uzyovoys/aggregate/commit/c6ec8c38ec9e9158d8f940f8f9e5f7e8be30b4f5

**Comment by ivanbalashov239** [comment]
@Morfeusys  отличный фикс :)
Думаю нужен в конфиге агрегата параметр языка, и поддержка получения этого параметра всеми модулями при инициализации(при желании/необходимости)

**Comment by morfeusys** [comment]
@seniorivn согласен. но это задача самого Агрегата. А фикс нужен уже сейчас.

**Comment by ivanbalashov239** [comment]
@Morfeusys ну я так и сказал, отличный фикс :)
