### ISSUE TITLE
забиндил кнопку не работает(ни че не происходит)

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#19]

**Comment by Vladimir070381** [comment]
![default](https://cloud.githubusercontent.com/assets/15859399/13502816/9fe4b732-e17d-11e5-870f-c40576e8011d.png)

**Comment by morfeusys** [comment]
По логу видно что Агрегат начинает вас слушать, но вы видимо отжимаете кнопку.Пожалуйста, читайте документацию чуть внимательнее.

**Comment by Vladimir070381** [comment]
может не правильно написал?
зажимаю-говорю-отпускаю-, тишина и ни каких движений!

**Comment by morfeusys** [comment]
У вас не установлен модуль распознавания речи.

**Comment by Vladimir070381** [comment]
как не установлен?а гугля?ключ для чего я получал?

2016-03-03 23:23 GMT+03:00 Dmitry Che notifications@github.com:

**Comment by morfeusys** [comment]
По логам видно что не установлен

**Comment by Vladimir070381** [comment]
все заработало!!!!!!2 дня танцев с бубном принесли результат:-)теперь
браузер не открывает!с рабочего стола?модуль браузер стоит

2016-03-04 11:22 GMT+03:00 Dmitry Che notifications@github.com:
