### ISSUE TITLE
aggregate слушает микрофон всё время, после первой активации с клавиатуры.

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#20]
какие логи показать не знаю, посмотрел в pavucontrol на linux.

Вопрос в том рационально ли такое поведение.

**Comment by morfeusys** [comment]
Агрегат так не делает. Ему это не нужно. Скорее всего либо у вас не приходит сообщение с клавиатуры о том что кнопка уже отжата, либо вы назначили только одну кнопку, и каждый раз при нажатии Агрегат включается. Назначьте две кнопки. Посмотрите в логах - прекращает ли вас слушать Агрегат. Это видно в окне консоли в которой он запущен.

**Comment by ivanbalashov239** [comment]
``` java
Mar 04, 2016 12:22:16 AM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65027]
Mar 04, 2016 12:22:16 AM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65027, 65515]
Mar 04, 2016 12:22:16 AM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 04, 2016 12:22:16 AM Dispatcher
INFO: Listening...
Mar 04, 2016 12:22:16 AM Dispatcher
INFO: ASR state: start
Mar 04, 2016 12:22:16 AM Dispatcher
INFO: ASR state: rec
Mar 04, 2016 12:22:17 AM Dispatcher
INFO: ASR state: done
Mar 04, 2016 12:22:17 AM Dispatcher
INFO: ASR state: end
Mar 04, 2016 12:22:18 AM Dispatcher
INFO: Processing...
Mar 04, 2016 12:22:18 AM Dispatcher
INFO: Processing Сколько время сколько время
Mar 04, 2016 12:22:18 AM Dispatcher
INFO: Processed in 4 ms: cmd.datetime.time

```

всё это время микрофон активен, активация по двум клавишам, попробую сменить комбинацию.

**Comment by ivanbalashov239** [comment]
``` java
Mar 04, 2016 12:32:52 AM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65515]
Mar 04, 2016 12:32:52 AM com.aggregate.detector.key.KeyDetector
INFO: Keys: [65513, 65515]
Mar 04, 2016 12:32:52 AM com.aggregate.detector.key.KeyDetector
INFO: Keyset detected
Mar 04, 2016 12:32:52 AM Dispatcher
INFO: Listening...
Mar 04, 2016 12:32:52 AM Dispatcher
INFO: ASR state: start
Mar 04, 2016 12:32:52 AM Dispatcher
INFO: Processing...
Mar 04, 2016 12:32:52 AM Dispatcher
INFO: ASR state: rec
Mar 04, 2016 12:32:55 AM Dispatcher
INFO: ASR state: done
Mar 04, 2016 12:32:55 AM Dispatcher
INFO: ASR state: end
Mar 04, 2016 12:32:55 AM Dispatcher
INFO: Processing...
Mar 04, 2016 12:32:55 AM Dispatcher
INFO: Processing Сколько время
Mar 04, 2016 12:32:55 AM Dispatcher
INFO: Processed in 0 ms: cmd.datetime.time

```

сменил комбинацию, ситуация аналогична, надо бы проверить воспроизводится ли в аналогичном окружении у кого-то другого(linux, pulseaudio и тп)

**Comment by morfeusys** [comment]
По логам видно что ASR закончил распознавание успешно и перестал писать звук. Так что физически он вас не слушает. То что микрофон "активен" - скорее всего просто потому что Java подключена к нему. Если его отпускать, то на подключение будет уходить время в несколько десятых секунды каждый раз при активации.

**Comment by ivanbalashov239** [comment]
@Morfeusys в #15 которые я посчитал связанными, нет сигнала завершения

``` java
INFO: ASR state: end
```

Я так понимаю это как раз означает, что агрегат мог не закончить слушать.
Впрочем если это java продолжает слушать, то пусть будет, мне не жалко, просто обычно программы так себя не вели.

**Comment by morfeusys** [comment]
@seniorivn нет, это как раз означает что модуль распознавания гарантированно закончил слушать. Java вас тоже не слушает. Просто она держит подключение к аппаратной части микрофона в "горячем" состоянии. Ибо например на таких девайсах как Raspberry Pi это может занимать время. А время при активации и голосовом взаимодействии - очень ценно.

**Comment by ivanbalashov239** [comment]
@Morfeusys  Про java понял, потом нужно будет сделать эту возможность опциональной, наверное.
Остальное обсудим в #15
