### ISSUE TITLE
директория deploy

### ISSUE THREAD

**Issue by vua4loj** [uzyovoys/aggregate#21]
Подскажите. Мы все модули кладем в директорию deploy. После запуска батника модули из этой директории исчезают. Это нормально? В терминале правда вижу реакцию на клавиатуру. Значит модуль работает. Только уда он делся?

**Comment by morfeusys** [comment]
Это нормально. После установки файл должен пропасть. Так как иначе он будет загружаться заново каждый раз при запуске.
