### ISSUE TITLE
как сделать чтоб браузер открывал?

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#22]

**Comment by morfeusys** [comment]
Поставить модуль https://github.com/uzyovoys/aggregate/tree/master/modules/browser

**Comment by Vladimir070381** [comment]
так я поставил,говорю открой браузер а в ответ тишина или же открывает на телефоне

**Comment by morfeusys** [comment]
Читайте внимательнее, для чего этот модуль и какие команды он обрабатывает

**Comment by Vladimir070381** [comment]
так мой вопрос не про модуль!а как сделать чтоб браузер открыал(про модуль
это Вы писали

6 марта 2016 г., 12:58 пользователь Dmitry Che notifications@github.com
написал:

**Comment by morfeusys** [comment]
Модуль написать, который открывает любые приложения

**Comment by Vladimir070381** [comment]
да я уже понял,я не волоку в этом!

2016-03-06 15:34 GMT+03:00 Dmitry Che notifications@github.com:
