### ISSUE TITLE
установка и удаление модулей

### ISSUE THREAD

**Issue by vua4loj** [uzyovoys/aggregate#24]
Вопрос по удалению модулей. 
Убрать в поле modules ссылку на модуль - это понятно. При этом если используется файл типа tts-yandex.json из директории conf убирать надо?
Вопрос по повторной установки модуля.
Если файл типа tts-yandex.json удалять не надо, то достаточно модуль снова отправить в директорию deploy. Я правильно понимаю?

**Comment by Vladimir070381** [comment]
мне тоже интересно!

**Comment by morfeusys** [comment]
Да, вы все правильно понимаете. Файл конфигурации удалять не обязательно. После удаления модуля просто перезапустите Агрегат.
