### ISSUE TITLE
файл грамматик vs конфиг файл

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#27]
В вики кажется нет упоминаний, возможно ли добавлять новые грамматики из конфига при инициализации модуля в методе `start()` теоретически можно редактировать/генерировать xml файл, перед привязкой команд к агрегату, но мне представляется это не правильным.

**Comment by morfeusys** [comment]
Стоит немного подождать. Функция "генерации" шаблонов "на лету" (подобно именам контактов или приложений в Дусе) - есть такая возможность. Но это в ближайших версиях агрегата.

**Comment by ivanbalashov239** [comment]
@Morfeusys ок, пока обойдемся без них.

**Comment by ivanbalashov239** [comment]
@Morfeusys подумал какие модули сделать и понял, что нужнее всего мне именно простой запуск своих скриптов и программ, по простым ключевым словам/названиям, хардкодить их в модуль можно, но неудобно, было бы лучше "на лету" так что голосую за поднятие приоритета этой фичи.

**Comment by morfeusys** [comment]
@seniorivn Реализовано в 0.0.2 [Динамические шаблоны](https://github.com/uzyovoys/aggregate/wiki/%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B)
