### ISSUE TITLE
Насколько сложно добавить другой язык в распознование морфологических структур агрегата?

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#28]
Интересны перспективы расширения проекта на другие языковые рынки.

**Comment by morfeusys** [comment]
Абсолютно несложно. Система полностью языконезависимая. Читайте документацию - она уже почти завершена.

**Comment by ivanbalashov239** [comment]
@Morfeusys аа, понял, это просто регекспы, круто :)

**Comment by morfeusys** [comment]
@seniorivn Это далеко не регекспы )) с точки зрения формализма - это контекстно-свободная грамматика, а не регулярка. Потому как регулярками естественную речь не описать в простом и читаемом виде.

**Comment by ivanbalashov239** [comment]
@Morfeusys  дада, у меня как раз только что был семестр формальных языков, это я просторечно обозвал.
