### ISSUE TITLE
как сделать чтоб Дуся дергала гугля?

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#30]
я пользуюсь и гуглем и Дусей одновременно,например погоду инфа от гугля,как мне прослушать погоду  через агрегат?

**Comment by morfeusys** [comment]
Агрегат работает через модули. Есть модуль для связки с дусей. Модуля для работы с окей гугл конечно же нет )) Но модуль поиска скорее всего будет сделан в ближайшее время.

**Comment by Vladimir070381** [comment]
ну я на это и намекаю:-)

5 марта 2016 г., 11:04 пользователь Dmitry Che notifications@github.com
написал:
