### ISSUE TITLE
танцы с бубном

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#4]
Дмитрий как Вы думаете много пользователей будут пользоваться активацией голоса с таким запуском голосового сервиса гугл:-)

**Comment by Vladimir070381** [comment]
и почему то не один модуль не устанавливается?тока скачивается и все:-(

**Comment by morfeusys** [comment]
Вы кажется забываете, что вы сейчас тестируете. А именно - альфа версию. 
Где вы увидели активацию голосом? Это никакая не активация голосом. Это просто распознавание команд. Модуля активации голосом вообще еще нет.

А насчет запуска модулей - сразу вижу, что документацию (Руководство пользователя) не читали )) Почитайте внимательнее..

Засим ваш тикет закрываю.

**Comment by Vladimir070381** [comment]
я просто про бубны долго танцевал не получается! и  как установку модуля забыл:-)

**Comment by morfeusys** [comment]
Все на танцпол!
