### ISSUE TITLE
модуль tts-yandex из папки deploy не убирается 

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#41]
@Oire процитирую предыдущий разговор

> >   P.S. У меня всё работает штатно, но модуль tts-yandex из папки deploy не убирается и соответственно в модулях json не появляется.
> 
> Попробуй убрать tts-yandex из aggregate.json, запустить агрегат и когда он инициализирует все плагины, обработает удаление, добавить новый ттс
> 
> @seniorivn, в том-то и прикол, что у меня в aggregate.json его никогда не было и нет(
> 
> @Oire а в консоли он что говорит когда находит jar в deploy? должен вывести ошибку если не смог инициализировать.
> 
> @seniorivn, как бы вам сказать... дело в том, что я работаю без зрения, а следовательно, с клавиатуры. И пока я просмотрю консоль, у меня весь экран занимают фидбэки от keyDetector, поэтому я не могу понять, в чём дело :(. По поводу эмоции для каждой фразы... даже не знаю, как это реализовать. Это такой же параметр урла, как и текст, например.

**Comment by ivanbalashov239** [comment]
@Oire попробуйте следующее(надеюсь у вас unix/linux)
`./start_debug.sh 2>&1 | grep -i tts -A 2 -B 2`
A,B это параметры количества строк до и после строки включающей найденную, которые нужно вывести. решил, что двух до и двух после, для понимания ситуации вам хватит.

**Comment by ivanbalashov239** [comment]
@Oire а ещё не стесняйтесь копировать весь вывод сюда, при проблемах, вместе разберёмся.

**Comment by Menelion** [comment]
Да в том-то и дело, что у меня Windows.

**Comment by ivanbalashov239** [comment]
@Oire очень жаль, тогда могу дать такую [ссылку](https://technet.microsoft.com/en-us/library/bb490907.aspx) это аналог grep судя по описанию.
по аналогии с моим примером примените.

**Comment by niksher23** [comment]
Тоже самое не убирается из deploy и не прописывается в aggregate.json, ос windows.Сначала подумал что он вообще не может установиться. Но всё работает. В консоли заметил  6 раз повторяется  resolving.

Launching the Aggregate runtime...
ьрЁ 08, 2016 5:18:32 AM Aggregate
INFO: Starting...
ьрЁ 08, 2016 5:18:32 AM Aggregate
INFO: Initializing with C:\Users\kolu\Desktop\agregat.\conf\aggregate.json
ьрЁ 08, 2016 5:18:32 AM Aggregate
INFO: Shell service is started
ьрЁ 08, 2016 5:18:32 AM ModuleRegistry
INFO: Auto deploy tts-yandex-1.0.0.jar
ьрЁ 08, 2016 5:18:32 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:key-detector:1.0.0::key-detector
ьрЁ 08, 2016 5:18:32 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:asr-google:1.0.0::asr-google
ьрЁ 08, 2016 5:18:32 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:dusi:1.0.0::dusi
ьрЁ 08, 2016 5:18:33 AM ModuleRegistry
INFO: Deploying with conf C:\Users\kolu\Desktop\agregat.\conf\key-detector.json
ьрЁ 08, 2016 5:18:33 AM Aggregate
INFO: Module registry is initialized
ьрЁ 08, 2016 5:18:33 AM ModuleRegistry
INFO: Deploying with conf C:\Users\kolu\Desktop\agregat.\conf\asr-google.json
ьрЁ 08, 2016 5:18:33 AM vertx-stack-resolver
INFO: Resolving com.aggregate:key-detector:jar:1.0.0
ьрЁ 08, 2016 5:18:33 AM ModuleRegistry
INFO: Deploying with conf C:\Users\kolu\Desktop\agregat.\conf\dusi.json
ьрЁ 08, 2016 5:18:33 AM ModuleRegistry
INFO: Deploying module maven:com.aggregate:tts-yandex:1.0.0::tts-yandex
ьрЁ 08, 2016 5:18:33 AM ModuleRegistry
INFO: Deploying with conf C:\Users\kolu\Desktop\agregat.\conf\tts-yandex.json
ьрЁ 08, 2016 5:18:33 AM vertx-stack-resolver
INFO: Resolving com.aggregate:tts-yandex:jar:1.0.0
ьрЁ 08, 2016 5:18:35 AM vertx-stack-resolver
INFO: Resolving com.aggregate:asr-google:jar:1.0.0
ьрЁ 08, 2016 5:18:35 AM vertx-stack-resolver
INFO: Resolving com.aggregate:tts-yandex:jar:1.0.0
ьрЁ 08, 2016 5:18:36 AM vertx-stack-resolver
INFO: Resolving com.aggregate:dusi:jar:1.0.0
ьрЁ 08, 2016 5:18:37 AM vertx-stack-resolver
INFO: Resolving com.aggregate:key-detector:jar:1.0.0
ьрЁ 08, 2016 5:18:38 AM vertx-stack-resolver
INFO: Resolving com.aggregate:asr-google:jar:1.0.0

JNativeHook: Global keyboard and mouse hooking for Java.
Copyright (C) 2006-2015 Alexander Barker.  All Rights Received.
https://github.com/kwhat/jnativehook/

JNativeHook is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

JNativeHook is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see http://www.gnu.org/licenses/.

ьрЁ 08, 2016 5:18:38 AM ModuleRegistry
INFO: Module maven:com.aggregate:key-detector:1.0.0::key-detector has been deployed
ьрЁ 08, 2016 5:18:39 AM vertx-stack-resolver
INFO: Resolving com.aggregate:dusi:jar:1.0.0
ьрЁ 08, 2016 5:18:39 AM ModuleRegistry
INFO: Module maven:com.aggregate:asr-google:1.0.0::asr-google has been deployed
ьрЁ 08, 2016 5:18:39 AM ModuleRegistry
INFO: Module maven:com.aggregate:dusi:1.0.0::dusi has been deployed
ьрЁ 08, 2016 5:18:39 AM Dispatcher
INFO: Module maven:com.aggregate:dusi:1.0.0::dusi has been loaded with 1 commands

**Comment by ivanbalashov239** [comment]
@niksher23 попробуйте удалить этот модуль из deploy, запустить агрегат, убедиться что он не загрузил key-detector, а потом закинуть модуль в deploy. И не забудьте конфиг для модуля написать.
P.S. используйте разметку markdown, консоль оформляйте как код

**Comment by XDedX** [comment]
Аналогичная проблема, key-detector не инсталлирован вообще

**Comment by niksher23** [comment]
Вообщем скомпилировал 1.1, пробовал и после запуска кидать в деплой, и при выключенной программе. Не удоляет из deploy и не добавляет в aggregate.json. Но при этом  инициализируется и всё работает.

> мар 09, 2016 1:25:14 AM ModuleRegistry
> INFO: Auto deploy tts-yandex-1.1.0.jar
> мар 09, 2016 1:25:14 AM ModuleRegistry
> INFO: Deploying module maven:com.aggregate:tts-yandex:1.1.0::tts-yandex
> мар 09, 2016 1:25:14 AM ModuleRegistry
> INFO: Deploying with conf C:\Users\kolu\Desktop\agregat.\conf\tts-yandex.json
> мар 09, 2016 1:25:14 AM vertx-stack-resolver
> INFO: Resolving com.aggregate:tts-yandex:jar:1.1.0

**Comment by morfeusys** [comment]
@niksher23 @XDedX сейчас агрегат пока не умеет обновлять модули. Поэтому предыдущую версию нужно удалять руками прежде чем ставить новую

**Comment by niksher23** [comment]
@Morfeusys  я так и делал, удалял из папки repository. Из  aggregate.json удалять не пришлось так как туда не прописывается.

**Comment by morfeusys** [comment]
Исправлено в 0.0.2
