### ISSUE TITLE
Подключение к Git по SSH в Windows без PuttyGen на примере Eclipse Version: Mars.2 Release (4.5.2)

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#42]
- добр\* утр\* \* сказал я Дусе и услышал в ответ стандартный набор фраз из скрипта (Доброе утро)

Много статей прочитал по подключению к Git по SSH-ключам. Почти во всех из них используется один из двух способов: либо с помощью puttygen.exe, либо командами ssh-keygen или ssh-add.
Мои попытки сгенерировать ключи, указать пути в переменных среды, привязать ключи к гиту были бесполезны. Либо гит ругался крякозябрами (в случае ssh-agent cmd.exe), либо просто игнорировал всё предложенное...

Issues #39 можно удалить.

**Comment by morfeusys** [comment]
А зачем вам гит по ssh обязательно??

**Comment by UUSR** [comment]
@Morfeusys у меня не получается синхронизировать свой Fork средствами Eclipse.

**Comment by morfeusys** [comment]
@UUSR я кажется в мануале про eclipse показал как работать со своим форком - там не нужен никакой ssh. Просто клонируете, потом импортируете проекты, создаете свои и потом делаетет коммит и пуш.

**Comment by UUSR** [comment]
@Morfeusys спасибо ,всё получилось просто стояла сначала Eclipse Luna и в ней меню Team было пустое и я не мог сделать коммит и пуш. Обновил на последнюю версию и меню появилось.
Дальше я должен сделать pull requests ?

**Comment by morfeusys** [comment]
Когда у вас будет уже все готово в вашем модули и он будет работать - вы _можете_ сделать пул реквест при желании, чтобы ваш код попал в основной репозиторий.
