### ISSUE TITLE
Создание файла README.md для модуля my-brain. 

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#44]
Интересно ,какая структура у этого файла?

**Comment by morfeusys** [comment]
Это обычный текстовик, где можно использовать markdown разметку. Тогда гитхаб будет ее красиво форматировать в веб браузере.

**Comment by UUSR** [comment]
@Morfeusys "Реализации Markdown на различных языках программирования включены (или доступны в качестве плагина)". В Eclipse эта разметка присутствует ?

**Comment by morfeusys** [comment]
@UUSR Это просто разметка. Необязательно иметь ее "поддержку", чтобы написать текст с его использованием. Я просто пишу в текстовике, или прямо на гитхабе.

**Comment by UUSR** [comment]
@pastukhov @seniorivn @vua4loj Прошу активнее голосовать за новый функционал и предлагать идеи для реализации.

**Comment by ivanbalashov239** [comment]
@UUSR где голосовать? вы о чем?
Эту issue можно уже закрыть, раз вы всё выяснили по теме.

**Comment by UUSR** [comment]
@seniorivn подождём ,пока рано закрывать

**Comment by ivanbalashov239** [comment]
@UUSR а что будем ждать?

**Comment by UUSR** [comment]
@seniorivn будем ждать остальных заинтересованных пользователей.

**Comment by ivanbalashov239** [comment]
@UUSR у вас проблемы с редактированием markdown? https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/

**Comment by UUSR** [comment]
@seniorivn спасибо исправил кодировку ,сейчас отображается без ошибок.
