### ISSUE TITLE
Не работает asr-google

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#47]
Установил хакинтош(10.9.3, есть интернет), при установке модуля распознавания речи вылетает:
`SEVERE: Cannot deploy maven:com.aggregate:asr-google:1.0.0::asr-google
io.vertx.core.impl.NoStackTraceThrowable: No data line is available`

**Comment by morfeusys** [comment]
У программы нет доступа к микрофону - как и написано в логе.
