### ISSUE TITLE
не появляется в папке conf

### ISSUE THREAD

**Issue by Vladimir070381** [uzyovoys/aggregate#5]
установил  все  корень C скопировал модули  папку deploy

**Comment by Vladimir070381** [comment]
или от тут нужно править что то?
"modules" : [ "maven:com.aggregate:browser:1.0.0::browser", "maven:com.aggregate:key-detector:1.0.0::key-detector", "maven:com.aggregate:date-time:1.0.0::date-time", "maven:com.aggregate:dictation:1.0.0::dictation" ]

**Comment by morfeusys** [comment]
В папке conf ничего и не должно появляться
