### ISSUE TITLE
[detector.key.KeyDetector| .Dictation] дублирование функционала

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#50]
Посмотрел модуль dictation, там так же как и в keydetector есть

``` java
    private Set<Integer> keySet = new HashSet<>();
    private Set<Integer> pressedKeys = Collections.synchronizedSet(new HashSet<>());
```

и ловятся события клавиатуры, проверяются совпадения(аналогично keydetector)
Мне не нравится :)
Предлагаю всю проверку вынести в модуль keyDetector
Мне это представляется простым событием(методом keydetector), на вход объект содержащий набор клавиш для срабатывания и событие срабатывания.
@Morfeusys согласен?

**Comment by morfeusys** [comment]
@seniorivn не думаю. Так как все равно модулю-слушателю может потребоваться хранить где-то текущее состояние "нажатости-отжатости" нужных ему кнопок. Усложнение протокола здесь бессмысленно поэтому.

**Comment by ivanbalashov239** [comment]
@Morfeusys если будет 10 шорткатов от разных модулей, то в каждом придется реализовывать этот функционал, да и сигналов кловиш много посылается, совершенно лишних.
Модуль слушатель не нуждается в контроле чего-либо, он получает сигнал начала и конца, если попросит, и тп. Я сделаю прототип, посмотришь, обсудим.

**Comment by morfeusys** [comment]
@seniorivn Если ты о том, чтобы в конфигурации key-detector прописывать комбинации для других модулей. то я против. Так как key-detector не должен ничего знать о других модулях. Его дело - просто посылать события, когда кнопка нажата и отжата. И все.

**Comment by ivanbalashov239** [comment]
@Morfeusys согласен, я о другом, напишу покажу.

**Comment by morfeusys** [comment]
@seniorivn Если ты о передаче нажатых на текущий момент кнопок в виде массива - то да, можно. Но это некоторое усложнение протокола, ибо видимо нужно использовать JSON массив. Ну усложнение вполне приемлемое.

**Comment by ivanbalashov239** [comment]
Расслабься, я просто напишу, так быстрее, там и поговорим.

**Comment by morfeusys** [comment]
Да я как раз не напрягаюсь )) жду

**Comment by morfeusys** [comment]
@seniorivn Спасибо, сморжил
