### ISSUE TITLE
Разработка в ветке master

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#51]
Предлагаю разработку вынести в ветку dev
А в ветку master мержить только готовые изменения, тогда можно будет настроить auto build

**Comment by morfeusys** [comment]
@seniorivn рано. Сейчас совсем ранняя разработка. Автобилды можно и сейчас настроить. Я хотел заняться этим позже.

**Comment by ivanbalashov239** [comment]
@Morfeusys ок
