### ISSUE TITLE
[conf/aggregate.json]: Не удаляются старые версии модулей

### ISSUE THREAD

**Issue by Menelion** [uzyovoys/aggregate#53]
Собрал и поставил несколько новых модулей (Дусю, Яндекс.TTS, KeyDetector). В результате элемент `modules` в моём aggregate.json выглядит вот так:

```
"modules" : [ "maven:com.aggregate:date-time:1.0.0::date-time", "maven:com.aggregate:dictation:1.0.0::dictation", "maven:com.aggregate:browser:1.0.0::browser", "maven:com.aggregate:key-detector:1.0.0::key-detector", "maven:com.aggregate:asr-google:1.0.0::asr-google", "maven:com.aggregate:dusi:1.0.0::dusi", "maven:com.aggregate:tts-ivona:1.0.0::tts-ivona", "maven:com.aggregate:dusi:1.0.1::dusi", "maven:com.aggregate:date-time:1.0.1::date-time", "maven:com.aggregate:key-detector:1.1.0::key-detector" ]
```

**Comment by morfeusys** [comment]
Да, в Агрегате 0.0.1 ошибка с обновлением модулей, которые в названии имеют номер версии.

**Comment by UUSR** [comment]
@Morfeusys Если модуль при установке не удаляется из deploy ,хотя он установился и работает и в aggregate.json появилась строка с новым модулем "maven:com.aggregate:my-brain:0.0.1::my-brain".
То из deploy удалять файл с модулем?

**Comment by UUSR** [comment]
@Morfeusys Если устанавливаю модуль и в названии нет номера версии то из deploy исчезает файл сам при установке.

**Comment by morfeusys** [comment]
Обновление 0.0.2 исправляет эту проблему
