### ISSUE TITLE
Запрос JSON формата remote/reply не возвращает результат

### ISSUE THREAD

**Issue by XDedX** [uzyovoys/aggregate#55]
С запросом remote всё замечательно, Дуся реагирует. Что делаю не так?

curl -sS -X POST -H "Content-Type: application/json" -H "Accept: application/json" \
 -d '{"jsonrpc": "2.0", "id": "777", "text": "погода"}' http://api.dusi.mobi/remote/reply

**Comment by morfeusys** [comment]
@XDedX указываете какой-то странный id. У Дуси идентификатор устройства восьмизначный.

**Comment by XDedX** [comment]
@Morfeusys Три семерки - счастливое число:-), ну это же шаблон, чтобы не указывать свой реальный id. У меня команда 
curl -sS -X POST -H "Content-Type: application/json" -H "Accept: application/json" \
-d '{"jsonrpc": "2.0", "id": "myid", "text": "погода"}' http://api.dusi.mobi/remote
отрабатывается нормально, ответ слышу на планшете

**Comment by Morfeusys** [comment]
@XDedX Ой, да, там была ошибка небольшая - id нужно передавать не в JSON, а просто параметром типа http://api.dusi.mobi/remote/reply?id=myid

Сейчас исправляю

**Comment by Morfeusys** [comment]
@XDedX да, на сервере была ошибка, извиняюсь. Исправлено.

**Comment by morfeusys** [comment]
@XDedX Я извиняюсь, я неправильно описал протокол в справке. Нужно посылать не на http://api.dusi.mobi/remote/reply, а на просто http://api.dusi.mobi/remote, но указать в параметре `reply=true`. То есть запрос посылать на http://api.dusi.mobi/remote?reply=true

**Comment by XDedX** [comment]
Работает
