### ISSUE TITLE
[ detector.key.KeyDetector| KeyDetector.java ] предупреждение line 39 Java Problem

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#56]
`else {
            keySet.addAll(keys.getList());
        }`

**Comment by morfeusys** [comment]
Ну предупреждение - не огщибка же ))

**Comment by UUSR** [comment]
@Morfeusys да согласен ,но хотел спросить чем предупреждения чреваты, и потом они сильно мозолят глаза  в панели.
