### ISSUE TITLE
Другие зависимости для своего модуля (как добавить)

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#57]
Если ваш модуль имеет другие зависимости, то обязательно включайте их классы в сборку с помощью следующего плагина:
`<plugin>`
    `<groupId>org.apache.maven.plugins</groupId>`
    `<artifactId>maven-shade-plugin</artifactId>`
    `<version>1.6</version>`
    `<configuration>`
        `<createDependencyReducedPom>true</createDependencyReducedPom>`
    `</configuration>`
    `<executions>`
        `<execution>`
            `<phase>package</phase>`
            `<goals>`
                `<goal>shade</goal>`
            `</goals>`
        `</execution>`
    `</executions>`
`</plugin>`
Куда добавлять этот плагин?
Как прописать в нём зависимости?

**Comment by ivanbalashov239** [comment]
Если в кратце, в файле pom.xml этот плагин нужно добавить в `<build>`, а ваши зависимости  в `<dependencies>`
http://www.tutorialspoint.com/maven/maven_pom.htm
вот нашел вам простенький, туториал(на первый взгляд толковый).

**Comment by UUSR** [comment]
@seniorivn спасибо ,почитаю на досуге.

**Comment by morfeusys** [comment]
@UUSR просто посмотрите не поленитесь на исходники модуля, у которого есть зависимости. Например tts-ivona. Там все станет понятно.
ПС. В плагине никаких зависимостей не прописывается. Они прописываются в поме.

**Comment by UUSR** [comment]
@Morfeusys я уже понял ,что прописывать в pom.xml правда я не знаю ещё какие зависимости мне нужны.

**Comment by UUSR** [comment]
@Morfeusys в tts-ivona есть:
`<dependency>`
            `<groupId>com.ivona</groupId>`
            `<artifactId>ivona-speechcloud-sdk-java</artifactId>`
            `<version>0.3.0</version>`
        `</dependency>`
а у меня нет ничего

Надеюсь ,что vertx и api будет достаточно:
`<dependencies>`
        `<dependency>`
            `<groupId>io.vertx</groupId>`
            `<artifactId>vertx-core</artifactId>`
            `<version>3.2.1</version>`
            `<scope>provided</scope>`
        `</dependency>`
        `<dependency>`
            `<groupId>com.aggregate</groupId>`
            `<artifactId>api</artifactId>`
            `<version>0.0.1</version>`
         `<scope>provided</scope>`
        `</dependency>`
    `</dependencies>`

**Comment by ivanbalashov239** [comment]
@UUSR Что значит достаточно? если вы используете`aggregate api`, то он нужен в зависимостях, если не используете, то не нужен. `vertx` нужен в любом случае, тк модуль это реализация `io.vertx.core.Verticle`

 П.С. Раздел зависимостей вы правильно добавили, если не было.
`<dependencies></dependencies>`

**Comment by UUSR** [comment]
@seniorivn Для базы данных MySQL мы будем использовать драйвер JDBC.
В pom.xml добавляю:
`<dependency>`
            `<groupId>mysql</groupId>`
            `<artifactId>mysql-connector-java</artifactId>`
            `<version>5.1.38</version>`
            `<scope>provided</scope>`
 `</dependency>`
Добавляю в проект драйвер **mysql-connector-java-5.1.38-bin.jar** ,появляется **Referenced Libraries** с подключенным драйвером для работы с базой данных MySQL.

**Comment by morfeusys** [comment]
@UUSR вам не нужно указывать что он provided. Иначе он н будет включен в сборку. Читайте все же мануал по использованию мавена - иначе вряд ли получится.

**Comment by UUSR** [comment]
@Morfeusys читаю ещё раз: http://www.apache-maven.ru/ и про конфигурацию **pom.xml** , http://www.apache-maven.ru/project-file.html.
Про строку `<scope>provided</scope>` нет ни слова. Буду искать в другом месте.

**Comment by UUSR** [comment]
@Morfeusys @seniorivn может вместо `<scope>provided</scope>` нужно добаить `<scope>compile</scope>` ?

**Comment by morfeusys** [comment]
@UUSR compile используется по умолчанию. Так что эту строку можно вообще не указывать.
Про понятие scope в документации мавена не может быть НЕ написано - это важная опция

**Comment by UUSR** [comment]
Всё разобрался ,если `<scope>provided</scope>` то тянет за собой все зависимости.

**Comment by morfeusys** [comment]
@UUSR нет, если `<scope>provided</scope>`, то как раз не тянет зависимости в сборку. Слово provided означает, что нужные вам библиотеки предполагается что есть в рантайме и их не нужно добавлять в сборку.
