### ISSUE TITLE
Скрипт "Доброе утро"  на Агрегате под ubuntu не работает

### ISSUE THREAD

**Issue by XDedX** [uzyovoys/aggregate#58]
Доходит до даты и тухнет. Такой же результат выдает и JSON запрос. Это на Ubuntu

**Comment by UUSR** [comment]
@XDedX у меня всё работает, как на смартфоне так и через aggregat.

**Comment by XDedX** [comment]
@UUSR Винда?

**Comment by UUSR** [comment]
@XDedX да Windows ,подправьте заголовок issue ато ошибки выдаёт.

**Comment by XDedX** [comment]
@UUSR Пусть выдает. Судьба у него такая - реагировать на изменения

**Comment by morfeusys** [comment]
Работает на mac os x и windows 10. На убунте проверю завтра.

**Comment by XDedX** [comment]
@Morfeusys  Было бы неплохо

**Comment by morfeusys** [comment]
Проверил - все ок
