### ISSUE TITLE
Остановка проигрывания медиа во время распознавания речи

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#59]
В во вкладке google play music играет музыка, при старте распознавания музыка останавливается, но при окончании распознавания проигрывание не продолжается. Вместо этого при следующей попытке распознавания музыка включается.

**Comment by morfeusys** [comment]
Извините, не понял. Какая вкладка? У агрегата вообще нет такой функции.

**Comment by popovanton0** [comment]
Вкладка в Google Chrome, win 10

**Comment by morfeusys** [comment]
У агрегата нет функции управления музыкой. Он никак не влияет на то как на вашем ПК будет включаться или не включаться музыка. Это, я так понимаю, свойство вашего пк наверное..

**Comment by popovanton0** [comment]
странно...
