### ISSUE TITLE
Ошибка с потоками при запуске

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#60]
Текущая кодовая страница: 1251
Launching the Aggregate runtime...
мар 26, 2016 9:58:58 AM Aggregate
INFO: Starting...
мар 26, 2016 9:58:58 AM Aggregate
INFO: Initializing with C:\Users\popov\Desktop\aggreg_clean.\conf\aggregate.json
мар 26, 2016 9:59:00 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2389 ms, time limit is 2000
мар 26, 2016 9:59:01 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3390 ms, time limit is 2000
мар 26, 2016 9:59:02 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4390 ms, time limit is 2000
мар 26, 2016 9:59:02 AM Aggregate
INFO: Shell service is started
мар 26, 2016 9:59:02 AM ModuleRegistry
INFO: Auto deploy key-detector-1.0.0.jar
и далее как обычно

**Comment by UUSR** [comment]
@popovanton0 У меня asr-google подвисает при загрузке ,как и видно из лога:

INFO: Module maven:com.aggregate:asr-google:1.0.0::asr-google has been deployed
мар 27, 2016 1:50:29 AM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2256 ms, time limit is 2000
мар 27, 2016 1:50:26 AM vertx-stack-resolver

**Comment by morfeusys** [comment]
@popovanton0 где вы видите ошибку с потоками? В чем эта ошибка выражается в работе?
То что поток на вашей системе приостанавливается на некоторое время при старте - это еще не ошибка. Если бы в логах вам не сообщили об этом, вы бы ничего об этом не узнали ))
