### ISSUE TITLE
Должны ли быть модули мультиплатформенными ?

### ISSUE THREAD

**Issue by popovanton0** [uzyovoys/aggregate#63]
Должны ли модули, создаваемые сторонними разработчиками быть мультиплатформенными, обязательно ли это условие ?

**Comment by UUSR** [comment]
@popovanton0 в документации написано:

Агрегат не накладывает никаких ограничений ни на IDE, ни на способ реализации модуля, ни на сторонние библиотеки, которые ему могут понадобиться.

вы пишете свой ​​код , как набор verticles .

Verticles являются куски кода, которые получают развернуть и запустить его с помощью Vert.x.Verticles могут быть написаны на любом из языков, которые Vert.x поддерживает и одно приложение может включать в себя verticles, написанные на разных языках.

**Comment by popovanton0** [comment]
Ну вот например, я сделал модуль, который сохраняет файл в папку "C:\Windows\" и читает его содержимое. Если этот модуль запустить под OS X, то он выдаст ошибку, что такого пути нет. Должен ли я исправлять модуль и заставлять его работать и под os x, и под windows, и под linux ?

**Comment by morfeusys** [comment]
@popovanton0 Сам модуль необязательно должен быть мультиплатформенным. Как вы можете видеть, тот же модуль tts-mac только для Mac OS. 
Только вот хардкодить C:\Windows  не стоит - даже под виндой не у всех может оказаться именно такая директория ))
