### ISSUE TITLE
Не работает модуль TTS-IVONA 1.0.1 (aggregate 0.0.2)

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#65]
Не работает модуль TTS-IVONA 1.0.1 весит процессинг и не воспроизводит речь ,агрегат сильно подвисает при обращении к модулю.

лог:

> INFO:
>  Module maven:com.aggregate:tts-ivona:1.0.1::tts-ivona has been deployed
> апр 05, 2016 12:07:46 AM com.aggregate.detector.key.KeyDetector
> INFO: Keyset detected
> апр 05, 2016 12:07:46 AM Dispatcher
> INFO: Listening...
> апр 05, 2016 12:07:46 AM Dispatcher
> INFO: ASR state: start
> апр 05, 2016 12:07:46 AM Dispatcher
> INFO: ASR state: rec
> апр 05, 2016 12:07:48 AM Dispatcher
> INFO: ASR state: done
> апр 05, 2016 12:07:49 AM Dispatcher
> INFO: ASR state: end
> апр 05, 2016 12:07:49 AM Dispatcher
> INFO: Processing...

,пока откатился на версию 1.0.0 и TTS завёлся.

**Comment by morfeusys** [comment]
Процессинг к tts не имеет никакого отношения. Tts ivona работает - проверено. Попробуйте еще.
