### ISSUE TITLE
Не работает Telnet (agregate 0.0.2)

### ISSUE THREAD

**Issue by UUSR** [uzyovoys/aggregate#66]
Не работает Telnet

лог:

> Microsoft
>  Telnet> open localhost 5000
> Подключение к localhost...Не удалось открыть подключение к этому узлу, на порт 5
> 000: Сбой подключения

**Comment by morfeusys** [comment]
В конфигурации его нужно включить - поле enabled

**Comment by UUSR** [comment]
@Morfeusys поменял в aggregate.json `"enabled" : false,` на  `"enabled" : true,` и всё заработало.
