### ISSUE TITLE
key-detector поддержка клавиш мыши

### ISSUE THREAD

**Issue by ivanbalashov239** [uzyovoys/aggregate#7]
У меня в Arch Linux при нажатии клавиш мыши(Thinkpad trackpoint keys) не отображаются коды в выхлопе key-detector.

**Comment by morfeusys** [comment]
И не должны. Это ж активация с кнопок клавы. Ну мышь тоже можно запилить, если хочется.

**Comment by ivanbalashov239** [comment]
ну, мне кажется было бы логично сделать их в одном модуле(для диктовки тоже справедливо) Например, если на мышь многокнопочная, может быть желание на второстепенную кнопку повесить запуск агрегатора, а дитковку вообще можно на среднюю кнопку мыши или alt+mouse1 как то так.
